name: NASA Planetary Travel CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.10.0
      #        with:
      #          mongodb-version: '4.4.6'
      #          auth: 'true'
      #          username: ${{ secrets.MONGODB_USERNAME }}
      #          password: ${{ secrets.MONGODB_PASSWORD }}
      #          port: 27017
      #          database: 'test'
      #          ip: '
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
